{{- if .Values.httpRoute.gateway.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.httpRoute.gateway.name }}
  namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.httpRoute.gateway.className }}

  {{- with .Values.httpRoute.gateway.infrastructure }}
  infrastructure:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  listeners:
    - name: {{ .Values.httpRoute.gateway.sectionName }}
      port: {{ .Values.httpRoute.gateway.port }}
      hostname: {{ .Values.global.domain.opencloud | quote }}

      {{- if .Values.global.tls.enabled }}
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.global.tls.secretName }}
            namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      {{- else }}
      protocol: HTTP
      {{- end }}

      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
    {{- end }}
    {{- if .Values.collaboration.enabled }}
    {{- if .Values.global.tls.enabled }}
    - name: collaboration-https
    {{- else }}
    - name: collaboration-http
    {{- end }}
      {{- if .Values.global.tls.enabled }}
      protocol: HTTPS
      {{- else }}
      protocol: HTTP
      {{- end }}
      port: {{ .Values.httpRoute.gateway.port }}
      hostname: {{ .Values.global.domain.wopi | quote }}
      {{- if .Values.global.tls.enabled }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.global.tls.secretName }}
            namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
    {{- end }}
{{- end }}
