{{- if and (not .Values.collabora.existingSecret) .Values.collabora.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: collabora
type: Opaque
stringData:
  username: {{ .Values.collabora.username }}
  password: {{ .Values.collabora.password }}
{{- end }}