{{- if and (not .Values.postgres.existingsecret) .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
{{- end }}