{{- if and (not .Values.postgres.existingSecret) .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.user }}
  password: {{ .Values.postgres.password }}
{{- end }}