{{- if and .Values.httpRoute.enabled .Values.oidc.issuerUrl .Values.oidc.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-keycloak-http-redirect
  namespace: {{ .Values.oidc.httpRoute.serviceNamespace | default .Release.Namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      {{- with .Values.httpRoute.gateway.sectionName }}
      sectionName: {{ . }}-keycloak-http
      {{- end }}
  hostnames:
    - {{ .Values.global.domain.oidc | quote }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: {{ .Values.global.domain.oidc }}
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-keycloak-httproute
  namespace: {{ .Values.oidc.httpRoute.serviceNamespace | default .Release.Namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      {{- with .Values.httpRoute.gateway.sectionName }}
      sectionName: {{ . }}-keycloak-https
      {{- end }}
  hostnames:
    - {{ .Values.global.domain.oidc | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.oidc.httpRoute.serviceName | default "keycloak" }}
          namespace: {{ .Values.oidc.httpRoute.serviceNamespace | default .Release.Namespace }}
          port: {{ .Values.oidc.httpRoute.port | default 80 }}
{{- end }}