{{- if and (not .Values.keycloak.existingSecret) .Values.keycloak.internal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
type: Opaque
stringData:
  adminUser: {{ .Values.keycloak.adminUser }}
  adminPassword: {{ .Values.keycloak.adminPassword }}
{{- end }}