global:
  domain:
    opencloud: opencloud.127.0.0.1.nip.io
    wopi: wopiserver.127.0.0.1.nip.io
    collabora: collabora.127.0.0.1.nip.io
    onlyoffice: onlyoffice.127.0.0.1.nip.io
    companion: companion.127.0.0.1.nip.io

collabora:
  enabled: true
  ssl:
    enabled: false

oidc:
  enabled: false

opencloud:
  
  migration:
    enabled: false

  createDemoUsers: true # necessary for admin user creation

  config:
    csp: |-
      directives:
        child-src:
          - '''self'''
        connect-src:
          - '''self'''
          - 'blob:'
          - 'http://companion.127.0.0.1.nip.io/'
          - 'ws://companion.127.0.0.1.nip.io/'
          - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
          - 'http://keycloak.127.0.0.1.nip.io/'
        default-src:
          - '''none'''
        font-src:
          - '''self'''
        frame-ancestors:
          - '''self'''
        frame-src:
          - '''self'''
          - 'blob:'
          - 'https://embed.diagrams.net/'
          - 'http://collabora.127.0.0.1.nip.io/'
          - 'https://docs.opencloud.eu'
        img-src:
          - '''self'''
          - 'data:'
          - 'blob:'
          - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
          - 'http://collabora.127.0.0.1.nip.io/'
        manifest-src:
          - '''self'''
        media-src:
          - '''self'''
        object-src:
          - '''self'''
          - 'blob:'
        script-src:
          - '''self'''
          - '''unsafe-inline'''
          - 'http://opencloud.127.0.0.1.nip.io/'
        script-src-elem:
          - '''self'''
          - '''unsafe-inline'''
          - 'http://opencloud.127.0.0.1.nip.io/'
        style-src:
          - '''self'''
          - '''unsafe-inline'''
        worker-src:
          - '''self'''

  excludeServices: [] # necessary that idp runs

  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 10Gi
    config:
      accessMode: ReadWriteOnce
      size: 10Gi
  
  storage:
    mode: posixfs
    s3:
      enabled: false
    posixfs:
      persistence:
        size: 10Gi
        accessMode: ReadWriteOnce

httpRoute:
  enabled: true
  
  gateway:
    create: true
    # name: cilium-gateway
    # className: cilium
    # namespace: "kube-system"
    # sectionName: https