apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-config
  namespace: openldap
data:
  ###############################################################################
  # OpenLDAP Configuration (osixia/openldap)
  ###############################################################################
  LDAP_GLOBAL_DOMAIN: "opencloud.eu"
  OPENLDAP_REPLICA_COUNT: "1"
  OPENLDAP_REPLICATION_ENABLED: "false"
